export enum LeagueTypes {
    GET_LEAGUES_REQUEST = 'league/GET_LEAGUES_REQUEST',
    GET_LEAGUES_SUCCESS = 'league/GET_LEAGUES_SUCCESS',
    GET_LEAGUE_BY_ID_REQUEST = 'league/GET_LEAGUE_BY_ID_REQUEST',
    GET_LEAGUE_BY_ID_SUCCESS = 'league/GET_LEAGUE_BY_ID_SUCCESS',
}
