export enum StandingsTypes {
    GET_STANDINGS_REQUEST = 'league/GET_STANDINGS_REQUEST',
    GET_STANDINGS_SUCCESS = 'league/GET_STANDINGS_SUCCESS',
    GET_TEAMS_LEAGUE_SUCESS = 'league/GET_TEAMS_LEAGUE_SUCESS',
}
