export enum StandingsTypes {
    GET_STANDINGS_REQUEST = 'standing/GET_STANDINGS_REQUEST',
    GET_STANDINGS_SUCCESS = 'standing/GET_STANDINGS_SUCCESS',
    GET_PARTICIPATING_TEAMS_REQUEST = 'standing/GET_PARTICIPATING_TEAMS_REQUEST',
    GET_PARTICIPATING_TEAMS_SUCCESS = 'standing/GET_PARTICIPATING_TEAMS_SUCCESS',
    GET_TEAMS_LEAGUE_SUCESS = 'standing/GET_TEAMS_LEAGUE_SUCESS',
}
